server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Si le fichier/dossier demandé n'existe pas, on redirige vers index.html
        try_files $uri $uri/ /index.html;
    }
}
