mvn verify sonar:sonar \
  -Dsonar.projectKey=ton_projet_key \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
  -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
